branch-defaults:
  default:
    environment: HALAMPExampleProdEnvironment
environment-defaults:
  HALAMPExampleProdEnvironment:
    branch: null
    repository: null
global:
  application_name: HALAMPExampleProdApp
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/PHP 7.1 running on
    64bit Amazon Linux/2.6.5
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
