branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: aws-ha-lamp-example
  branch: master
  default_ec2_keyname: aws-ha-lamp-example
  default_platform: PHP 7.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: aws-ha-lamp-example
  sc: git
  workspace_type: Application
