AWSTemplateFormatVersion: 2010-09-09
Description: DNS Configuration
Parameters:
  AppName:
    Description: Name of the application.
    MaxLength: 100
    MinLength: 1
    Type: String
  Environment:
    Description: Environment suffix for services, an empty string is assumed to be production
    ConstraintDescription: Environment must be one of 'Dev' or 'Prod'
    Default: 'Prod'
    MinLength: 3
    MaxLength: 4
    Type: String
    AllowedValues:
      - 'Dev'
      - 'Prod'
  HostedZoneID:
    AllowedPattern: ^[A-Z0-9]+$
    ConstraintDescription: Must be a valid HostedZoneID, typically in the format of ABCDEFG123456
    Description: HostedZoneID either created by the Route53 Registrar (after registering a domain) or manually created
    Type: String
Mappings:
  SubDomain:
    Prod:
      Suffix: ''
    Dev:
      Suffix: 'dev'
  # AWS Hosted Zones are documented here by region and service: http://docs.aws.amazon.com/general/latest/gr/rande.html
  AWSHostedZones:
    us-east-1:
      APIGateway: Z1UJRXOUMOOFQ8
      CloudFront: Z2FDTNDATAQYW2
Resources:
  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneID
      RecordSets:
        - Name:
            Fn::ImportValue: !Sub "${AppName}${Environment}ACMWebsiteDomain"
          Type: A
          AliasTarget:
            HostedZoneId: !FindInMap [AWSHostedZones, !Ref "AWS::Region", 'CloudFront']
            DNSName:
              Fn::ImportValue: !Sub "${AppName}${Environment}WebBeanstalkURL"